Traceback (most recent call last):
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\users\fuzzbin\.pyenv\pyenv-win\versions\3.7.6\lib\site-packages\nbclient\client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy

def f(x):
    return x**2

x_verdier = numpy.linspace(0, 5, 6) # start, slutt, antall verdier
y_verdier = f(x_verdier)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[1;32m<ipython-input-3-3b6705611dc6>[0m in [0;36m<module>[1;34m[0m
[1;32m----> 1[1;33m [1;32mimport[0m [0mnumpy[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      2[0m [1;33m[0m[0m
[0;32m      3[0m [1;32mdef[0m [0mf[0m[1;33m([0m[0mx[0m[1;33m)[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m      4[0m     [1;32mreturn[0m [0mx[0m[1;33m**[0m[1;36m2[0m[1;33m[0m[1;33m[0m[0m
[0;32m      5[0m [1;33m[0m[0m

[1;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

