Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/usr/local/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
tuppel = (5, 6, 7, "Hoppsann", 8)
print(tuppel, "er en tuppel.")
print("I motsetning til en liste, er det ikke mulig Ã¥ endre verdiene i en tuppel.")
print("Den neste linja vil derfor gi en feilmelding")
tuppel[3] = "Heisann"

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-7-3283ac2c1375>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mprint[0m[0;34m([0m[0;34m"I motsetning til en liste, er det ikke mulig Ã¥ endre verdiene i en tuppel."[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mprint[0m[0;34m([0m[0;34m"Den neste linja vil derfor gi en feilmelding"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mtuppel[0m[0;34m[[0m[0;36m3[0m[0;34m][0m [0;34m=[0m [0;34m"Heisann"[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mTypeError[0m: 'tuple' object does not support item assignment
TypeError: 'tuple' object does not support item assignment

